### PR TITLE
Create PKGBUILD

### PR DESCRIPTION
**Pull request by Zaedus**
This is a draft for now because I want to ask for some of your input. For one, I really like where this project is heading, and I think I have rust under my belt that I might be of some assistance. Firstly, I would like to create a stable and a git version of the AUR package so that in case a breaking change is introduced, people can refer to the stable version in the AUR and it'll work. However, that will require that you get to some stable point and then mark the version. If you don't want to do a stable and git version, that's completely fine I will setup the git version and maintain it. Right now, I haven't put in any of the important building information awaiting what you have to say. Secondly, I can help with some development if need be. Just let me know I'll see what I can do.

### CODE REVIEW

**Comment by Siriusmart** [comment]
so that is working which is good
can you make mpv an optional dependency instead of a required one? because it isnt really required, also yt-dlp and konsole should be in the optional deps list as they are the default
the stable version is on crates.io

i need to make like an actual documentation thing and explain what the code is doing, thx :)

**Comment by Zaedus** [comment]
Alright, I can get right on that! Are mpv, konsole, and yt-dlp optional because they are defaults for something that can be changed? Also, what does konsole have to do with this project, like why is a terminal emulator needed?

**Comment by Zaedus** [comment]
Also, would a `youtube-tui-bin` be a good idea in your opinion?

**Comment by Siriusmart** [comment]
> Also, what does konsole have to do with this project, like why is a terminal emulator needed?

uhh so here's a case where mpv is opened in a new terminal emulator window or else it's basically impossible to stop

```yaml
audio_playlist_shuffle:
  args:
    - konsole
    - "-e" - mpv
    - "{embed_url}"
    - "--no-video"
    - "--shuffle"
```

and yt-dlp will just dump all the output in the current emulator window and the tui will be unusable until the download finishes

konsole is just the default

**Comment by Siriusmart** [comment]
> Also, would a `youtube-tui-bin` be a good idea in your opinion?

yeah that would be a good idea, I'm gonna start uploading compiled binary to github releases starting from the next release

**Comment by Zaedus** [comment]
Awesome! In reference to the mpv issue, what if we create an mpv socket (by specifying the `--ipc-socket` option) and control mpv through that? That way, we don't need to open a terminal emulator and we'll also have the ability to control playback, and maybe have only *one* mpv instance open at a time, so when playing a playlist, it'll change the video playing in the already open mpv window.

**Pull request merged**
